// config.ts
export const API_KEY = 'vtexappkey-lojapitu-JXXKAC';
export const API_SECRET = 'BRNGNXUKYBBKJIUVVUPRHQXDZSJZPGESCZANPCQINJDXUZMMBSLHOOHUOHVYHDQHGDSMFQDLDNCDAQSMCCPAZOGDUWMCYNFPQDSTLAAWOQBVCOINYCQQKEROUEHIIDXP';

